- name: install the bumblebee packages
  dnf: name={{ item }}
       state=present
  with_items:
    - bumblebee-nvidia
    - bbswitch-dkms
    - VirtualGL.x86_64
    - VirtualGL.i686
    - primus.x86_64
    - primus.i686
    - kernel-devel
