- name: install the i3 window manager packages
  dnf: name={{ item }}
       state=present
  ignore_errors: yes
  with_items:
    - i3
    - i3-doc
    - i3-ipc
    - i3lock
    - i3status
    - rofi
    - lightdm
    - lightdm-gtk
    - lightdm-gtk-greeter-settings
    - thunar
    - lxrandr
    - xbacklight
    - blueman
    - feh
    - scrot
    - ImageMagick
    - acpi
    - python3-tkinter
    - pavucontrol
    - polybar
    - pygtk2

- name: disable gdm
  systemd:
    name: gdm
    enabled: no

- name: enable lightdm
  systemd:
    name: lightdm
    enabled: yes

- name: copy i3-lock to /usr/local/bin
  copy:
    src: usr/local/bin/i3-lock
    dest: /usr/local/bin/i3-lock
    owner: root
    group: root
    mode: 0755

- name: copy suspend service to systemd
  copy:
    src: etc/systemd/system/suspend.service
    dest: /etc/systemd/system/suspend@{{ user }}.service
    owner: root
    group: root
    mode: 0644

- name: copy wallpaper to ~/.wallpaper
  copy:
    src: wallpaper/star-trek-beyond.jpg
    dest: /home/{{ user }}/.wallpaper.jpg
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
