- name: install the rpmfusion repo packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
  tags:
    - repos

- name: install the google repo packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
  tags:
    - repos

