---
- name: python2-dnf is required
  raw: rpm -q python2-dnf || dnf -y install python2-dnf

- name: All the required packages for my workstation
  dnf: name={{ item }}
       state=present
  with_items:
  - keychain
  - htop
  - libselinux-python
  - hplip-gui
