---
- name: check if python2-dnf is installed
  command: rpm -q python2-dnf
  register: installed
  ignore_errors: true
  changed_when: false
  args:
    warn: false # set warn=false to prevent warning
  tags:
    - skip_ansible_lint
    - required

- name: python2-dnf is required
  command: dnf -y install python2-dnf
  when: installed is failed
  args:
    warn: false # set warn=false to prevent warning
  tags:
    - required

- name: make sure ~/bin exists
  file:
    path: /home/{{ user }}/bin
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - required
