- name: install the virtualization packages
  dnf:
    name=@virtualization
    state=present
  tags:
    - virt

- name: install extra virtualization packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - libguestfs-tools
  tags:
    - virt

- name: start libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes
  tags:
    - virtualization

- name: add user to libvirt group
  user:
    name: "{{ user }}"
    groups: libvirt
    append: yes
  tags:
    - virtualization

- name: test if grub configured for hardware virt io
  command: egrep -q 'kvm-intel.nested=1' /boot/efi/EFI/fedora/grub.cfg
  register: grub_test
  changed_when: no
  failed_when: grub_test.rc == 2
  ignore_errors: yes
  check_mode: no
  tags:
    - virtualization

- name: configure grub for hardware virt io
  command: grubby --update-kernel=ALL --args=kvm-intel.nested=1
  when: grub_test.rc == 1
  ignore_errors: yes
  tags:
    - virtualization

