---
- name: create backup dir to mount disk to
  file:
    path: /mnt/backup
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: disk to mount
  mount:
    path: /mnt/backup
    src: "{{ disk }}"
    fstype: "{{ fstype }}"
    state: mounted
