- name: install the TLP repo packages Fedora 28
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc29.noarch.rpm
  when: ansible_distribution_major_version == '29'
  ignore_errors: true
  tags:
    - repos

- name: install the TLP repo packages Fedora 28
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc28.noarch.rpm
  when: ansible_distribution_major_version == '28'
  ignore_errors: true
  tags:
    - repos

- name: install the tlp packages
  package:
    name: "{{ item }}"
    state: present
  ignore_errors: yes
  with_items:
    - tlp
    - tlp-rdw
      #    - akmod-tp_smapi
      #- akmod-acpi_call
    - kernel-devel
  tags:
    - tlp
