- name: install the TLP repo packages Fedora 28
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.linrunner.de/fedora/tlp/repos/releases/28/x86_64/os/tlp-release-1.28.0-1.fc28.noarch.rpm
  when: ansible_distribution_major_version == '28'
  ignore_errors: true
  tags:
    - repos

- name: install the TLP repo packages Fedora 27
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.linrunner.de/fedora/tlp/repos/releases/27/x86_64/os/tlp-release-1.0.9-1.fc27.noarch.rpm
  when: ansible_distribution_major_version == '27'
  ignore_errors: true
  tags:
    - repos

- name: install the tlp packages
  dnf:
    name: "{{ item }}"
    state: present
  ignore_errors: yes
  with_items:
    - tlp
    - akmod-tp_smapi
    - akmod-acpi_call
    - kernel-devel
  tags:
    - tlp
