- name: install the TLP repo packages Fedora 30
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc30.noarch.rpm
  when: ansible_distribution_major_version == '30'
  ignore_errors: true
  tags:
    - repos

- name: install the TLP repo packages Fedora 31
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc31.noarch.rpm
  when: ansible_distribution_major_version == '31'
  ignore_errors: true
  tags:
    - repos

- name: install the tlp packages
  package:
    name: "{{ item }}"
    state: present
  ignore_errors: yes
  with_items:
    - tlp
    - tlp-rdw
    # - akmod-tp_smapi
    # - akmod-acpi_call
    - kernel-devel
  tags:
    - tlp
