---
- name: check if python2-dnf is installed
  raw: rpm -q python2-dnf
  register: installed
  ignore_errors: true
  changed_when: false
  tags:
    - required

- name: python2-dnf is required
  raw: dnf -y install python2-dnf
  when: installed|failed
  tags:
    - required

- name: make sure ~/bin exists
  file:
    path: /home/{{ user }}/bin
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - required
