---
- name: install the bumblebee repo packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - https://linux.itecs.ncsu.edu/redhat/public/bumblebee/fedora{{ ansible_distribution_major_version }}/noarch/bumblebee-release-1.3-1.noarch.rpm
    - https://linux.itecs.ncsu.edu/redhat/public/bumblebee-nonfree/fedora{{ ansible_distribution_major_version }}/noarch/bumblebee-nonfree-release-1.3-1.noarch.rpm
  when: ansible_distribution_major_version >= '27'
  tags:
    - bumblebee

- name: install the bumblebee packages
  dnf:
    name:  "{{ item }}"
    state: present
  with_items:
    - bumblebee-nvidia
    - bbswitch-dkms
    - VirtualGL.x86_64
    - VirtualGL.i686
    - primus.x86_64
    - primus.i686
    - kernel-devel
  ignore_errors: true
  tags:
    - bumblebee
