---
- name: install the bumblebee repo packages
  package:
    name: "{{bumblebee_repos}}"
    state: present
  when: ansible_distribution_major_version >= '30'
  ignore_errors: true
  tags:
    - bumblebee

- name: install the bumblebee packages
  package:
    name: "{{bumblebee_packages}}"
    state: present
  when: ansible_distribution_major_version >= '30'
  ignore_errors: true
  tags:
    - bumblebee
